### ISSUE TITLE
Does this library grammar handle content line folding properly?

### ISSUE THREAD

**Issue by jamespedid** [bkiers/ICalParser#6]
Hello, I'm looking to create an ical parser for nodejs using the grammar that is provided. Reading the spec, it is under the impression that a line should be folded every so many (75) octets; a folded line is one where there is a CLRF followed by a space. Does this grammar properly account for that?

**Comment by bkiers** [comment]
The grammar does not mandate the input to be folded every so many octets. 

However, a line break followed by one or more space chars is "unfolded" (skipped in the parsing stage).

Check the grammar:

```
LINE_FOLD
 : CRLF WSP -> skip
 ;
```
